---
abstract: 'perform exit processing for a program or object'
author:
  - 'Brad Appleton <brad@bradapp.net>'
build_requires:
  Capture::Tiny: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.133380'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AtExit
requires:
  Exporter: '0'
  perl: '5.002'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/AtExit
  repository: https://github.com/neilbowers/AtExit.git
version: 2.01_01
